version: '3.9'

services:
  app:
    env_file:
      - ./backend/.env.dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: palkkaakoodari_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    env_file:
      - ./backend/.env.dev
    image: postgres:15
    container_name: palkkaakoodari_postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
